### ISSUE TITLE
Error when init jqte over an input with dynamic value setted

### ISSUE THREAD

**Issue by marcosgallardo** [gauravspatel/jqueryte#1]
Hi there,

Let's review this sceneario:

```html
<input class="editor" name="details" />
```
```javascript
$('.editor').val('Coffe please!');
$('.editor').jqte();
```

**Expected result**: An **jQuery TE** with value equals to "_Coffe please!_"
**Actual result**: An **jQuery TE** with value equals to ""

**Comment by gauravspatel** [comment]
Feel free to send a note to the author: fattih@fattih.com.

I added this so I could use bower to get the files.
